### ISSUE TITLE
Load more players

### ISSUE THREAD

**Issue by kangwonlee** [kangwonlee/football-manager-pandas#2]
* 처음에는 선수 목록이 일부만 보입니다
* 목록 아래 끝에서 계속 <kbd>Load more players</kbd> 를 선택 해야 선수 목록을 추가해 볼 수 있습니다

**Comment by kangwonlee** [comment]
``` html
<a href="[#](https://fminside.net/players#)" class="loadmore">
Load more players..
</a>
```
* 해당 메뉴는 위 행의 작용으로 보입니다.
* https://fminside.net/resources/css/style.css?1662653871 에 아래와 같은 부분이 있습니다.
``` css
div.table a.loadmore {
    display: block;
    font-size: 15px;
    text-align: center;
    padding: 20px 0 0 0;
    margin: 0;
}
```
* 위 `href` 는 `https://fminside.net/players` 에서 `https://fminside.net/players#`를 선택하는 것으로 보입니다
